### ISSUE TITLE
Pyenv-mode-set returns "system", "/bin/bash/", "pyenv", "command", "not", "found"

### ISSUE THREAD

**Issue by JiaHong-Lee** [pythonic-emacs/pyenv-mode#32]
## Description
As per the title.

Not sure if this is relevant, I install pyenv by cloning the pyenv github repository to ~/.pyenv. Then add these to my .bashrc:
```bash
export PATH="/home/zacque/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

## Possible Cause
Upon inspection, I found
https://github.com/pythonic-emacs/pyenv-mode/blob/aec6f2aa289f6aed974f053c081143758dd142fb/pyenv-mode.el#L57
returns  "/bin/bash: pyenv: command not found". By running `bash -c pyenv` in a shell, it seems that pyenv is not found on my $PATH.

## Possible Workarounds
1. Use exec-path-from-shell package.
```emacs-lisp
(use-package exec-path-from-shell
  :config
  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize)))
```

2. Set $PATH environment variable.
```emacs-lisp
(use-package pyenv-mode
  ;; Integrate pyenv with Python-mode
  :init
  (let ((pyenv-path (expand-file-name "~/.pyenv/bin")))
    (setenv "PATH" (concat pyenv-path ":" (getenv "PATH")))
    (add-to-list 'exec-path pyenv-path))
  :config
  (pyenv-mode))
```

3. Move export PATH to ~/.profile.
```bash
export PATH="/home/zacque/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

## Package Suggestion
Add checking during activating pyenv-mode to see whether pyenv is on the $PATH. This can be done using `(executable-find "pyenv")`.

**Comment by Porcupine96** [comment]
I've had similar issue. Thank you for the workarounds @JiaHong-Lee (I went with the 2nd one).

**Comment by CeleritasCelery** [comment]
Thanks
